#-------------------------------
# General Site Settings

menu:
# - {name: 'works', url: ''}
- {name: 'works', url: 'pages/works.html'}
- {name: 'about', url: 'pages/about.html'}
- {name: 'contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio of photographer CAI Xiao'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # about


  

contact: >
  # contact

  







#-------------------------------
# Work Section

projects:

- {name: '颜色奇怪的风景', folder: '0001', file: 'works/0001.html', cover: 'https://pic.superbed.cn/item/5e31a9382fb38b8c3ceb0d49.jpg'}

- {name: '各种各样的绿色', folder: '0002', file: 'works/0002.html', cover: 'https://pic2.superbed.cn/item/5dd3b2208e0e2e3ee92350f2.jpg'}

- {name: '有颜色的风景', folder: '0003', file: 'works/0003.html', cover: 'https://pic3.superbed.cn/item/5de252318e0e2e3ee93f505d.jpg'}

- {name: '各种各样的绿色', folder: '0004', file: 'works/0004.html', cover: 'https://pic1.superbed.cn/item/5debcd08f1f6f81c50561dc7.jpg'}

- {name: '有颜色的风景・二', folder: '0005', file: 'works/0005.html', cover: 'https://pic3.superbed.cn/item/5df224431f8f59f4d69fef34.jpg'}

- {name: '在鹤岗的最后一个夏天', folder: '0006', file: 'works/0006.html', cover: 'https://pic2.superbed.cn/item/5df9a5d076085c32898322ad.jpg'}

- {name: '有颜色的风景・三', folder: '0007', file: 'works/0007.html', cover: 'https://pic.superbed.cn/item/5e35c9302fb38b8c3c45e3f2.jpg'}

- {name: '海拉尔', folder: '0008', file: 'works/0008.html', cover: 'https://pic.superbed.cn/item/5e09c5b576085c3289b5b073.jpg'}

- {name: '有颜色的风景・四', folder: '0009', file: 'works/0009.html', cover: 'https://pic.superbed.cn/item/5e36715e2fb38b8c3c5acf0b.jpg'}

- {name: '自选集', folder: '0010', file: 'works/0010.html', cover: 'https://pic.superbed.cn/item/5e32778d2fb38b8c3cfad94c.jpg'}

- {name: '有颜色的风景・五', folder: '0011', file: 'works/0011.html', cover: 'https://pic.imgdb.cn/item/5e39624b2fb38b8c3ca79ea4.jpg'}

- {name: '牙克石的诗', folder: '0012', file: 'works/0012.html', cover: 'https://pic.imgdb.cn/item/5e53cba46127cc07137d94c4.jpg'}

- {name: '有颜色的风景・六', folder: '0013', file: 'works/0013.html', cover: 'https://pic.imgdb.cn/item/5e5e720798271cb2b861b6cc.jpg'}

- {name: '郊区（这个城市以前叫凉州）', folder: '0014', file: 'works/0014.html', cover: 'https://pic.imgdb.cn/item/5e69bcf8e83c3a1e3aeb811f.jpg'}

- {name: '有颜色的风景・七', folder: '0015', file: 'works/0015.html', cover: 'https://pic.imgdb.cn/item/5e6f3c15e83c3a1e3a718bfd.jpg'}

- {name: '合作・一 ~ 二', folder: '0016', file: 'works/0016.html', cover: 'https://pic.imgdb.cn/item/5e880558504f4bcb046c4262.jpg'}

- {name: '有颜色的风景・八', folder: '0017', file: 'works/0017.html', cover: 'https://pic.imgdb.cn/item/5e74ae5dc8156f1e6fe96243.jpg'}

- {name: '合作・三 ~ 四', folder: '0018', file: 'works/0018.html', cover: 'https://pic.imgdb.cn/item/5e8805ad504f4bcb046c8999.jpg'}

- {name: '有颜色的风景・九', folder: '0019', file: 'works/0019.html', cover: 'https://pic.imgdb.cn/item/5e81e8ef504f4bcb044aba55.jpg'}

- {name: '合作・五 ~ 六', folder: '0020', file: 'works/0020.html', cover: 'https://pic.imgdb.cn/item/5e955aa1c2a9a83be59de0f0.jpg'}

- {name: '有颜色的风景・十', folder: '0021', file: 'works/0021.html', cover: 'https://pic.imgdb.cn/item/5e880c05504f4bcb047165d6.jpg'}

- {name: '合作・七 ~ 八', folder: '0022', file: 'works/0022.html', cover: 'https://pic.imgdb.cn/item/5ea58aeac2a9a83be513f44d.jpg'}

- {name: '有颜色的风景・十一', folder: '0023', file: 'works/0023.html', cover: 'https://pic.imgdb.cn/item/5e8b55dd504f4bcb0466d56a.jpg'}







#-------------------------------
# Contact Section

social:
#- {icon: 'envelope', link: 'mailto:#'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
